---
- name: Install Docker
  hosts: all
  become: true
  gather_facts: yes
  
  tasks:
  - name: Add apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags: install

  - name: Add repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker
    tags: install

  - name: Update repositories cache and install package
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - docker-ce
        - docker-ce-cli
        - containerd.io
#        - python3-docker
        - python3-pip
      state: latest
      update_cache: yes
    tags: install

  - name: Install docker package from pip
    pip:
      name: 
        - docker
        - docker-compose
    tags: install

  - name: "Add user {{ ansible_user }} to group docker"
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    tags: install

  - name: Start service
    service:
      name: docker
      state: started
      enabled: yes
    tags: install
