---
- name: Run Gitlab
  hosts: all
  become: true
  gather_facts: yes

  vars:
    gitlab_env:
      GITLAB_HOME: /srv/gitlab
    gitlab_token: GR1348941qM6TsnPVevXN5S2RBK3B

  tasks:
  - name: Run docker container
    community.docker.docker_compose:
      project_name: gitlab
      definition:
        version: '3.6'
        services:
          web:
            image: 'gitlab/gitlab-ce:latest'
            restart: always
            hostname: 'gitlab.example.com'
            environment:
              GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://{{ ansible_host }}'
                gitlab_rails['gitlab_shell_ssh_port'] = 2222
            volumes:
              - '$GITLAB_HOME/config:/etc/gitlab'
              - '$GITLAB_HOME/logs:/var/log/gitlab'
              - '$GITLAB_HOME/data:/var/opt/gitlab'
            ports:
              - '80:80'
              - '443:443'
              - '2222:22'
            shm_size: '256m'
            networks:
              - gitlab
          
          runner:
            image: 'gitlab/gitlab-runner:latest'
            restart: always
            volumes:
              - /srv/gitlab-runner/config:/etc/gitlab-runner
              - /var/run/docker.sock:/var/run/docker.sock
            networks:
              - gitlab

        networks:
          gitlab:
    environment: "{{ gitlab_env }}"

  - name: Pause for 1 minutes to install end
    pause:
      minutes: 1

  - name: Get password
    shell: docker exec -it gitlab_web_1 grep 'Password:' /etc/gitlab/initial_root_password | awk '{print $2}'
    register: password

  - name: Show password
    debug:
      msg: 
        - "URL: http://{{ ansible_host }}"
        - "Password: {{ password.stdout }}" 

  - name: Register runner
    shell: docker exec -it gitlab_runner_1 gitlab-runner register \
      --url http://{{ ansible_host }}/ \
      --non-interactive \
      --locked=false \
      --name local \
      --executor docker \
      --docker-image alpine:latest \
      --registration-token {{ gitlab_token }} \
      --tag-list "linux,xenial,ubuntu,docker" \
      --run-untagged