version: '3.3'

services:

  post_db:
    image: mongo:${REDDIT_DB_TAG}
    volumes:
      - post_db:/data/db
    networks:
      - reddit

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${REDDIT_UI_TAG}
    ports:
      - 9292:${REDDIT_UI_PORT}/tcp
    networks:
      - reddit

  post:
    #build: ./post-py
    image: ${USERNAME}/post:${REDDIT_POST_TAG}
    networks:
      - reddit

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${REDDIT_COMMENT_TAG}
    networks:
      - reddit

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - reddit

  node-exporter:
    image: prom/node-exporter:v1.3.1
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - reddit
volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
